document.write("<p align=\"center\">&nbsp;<\/p>");
document.write("<p align=\"center\">&nbsp;<\/p>");
document.write("<p align=\"center\">&nbsp;<\/p>");
document.write("<p align=\"center\">&nbsp;<\/p>");
document.write("<p align=\"center\">&nbsp;<\/p>");
document.write("<p align=\"center\">&nbsp;<\/p>");
document.write("<p align=\"center\">&nbsp;<\/p>");
document.write("");
document.write("");
document.write("<div class=\"Googol animated fadeInDownBig\" id=\"Logo\">");
document.write("");
document.write("<align=\"center\">");
document.write("");
document.write("<span class=\"Googol_Colour\">");
document.write("");
document.write("<span class=\"Googol\">G<\/span>");
document.write("");
document.write("<span class=\"Googol_Colour_0\">o<\/span>");
document.write("");
document.write("<span class=\"Googol_Colour_1\">o<\/span>");
document.write("");
document.write("<span class=\"Googol_Colour_2\">g<\/span>");
document.write("");
document.write("<span class=\"Googol_Colour_3\">o<\/span>");
document.write("");
document.write("<span class=\"Googol_Colour_4\">l<\/span> ");
document.write("");
document.write("<span class=\"Googol_Colour_5\">G<\/span>");
document.write("");
document.write("<span class=\"Googol_Colour_6\">L<\/span>");
document.write("");
document.write("<span class=\"Googol_Colour_7\">a<\/span>");
document.write("");
document.write("<span class=\"Googol_Colour_8\">D<\/span>");
document.write("");
document.write("<span class=\"Googol_Colour_9\">O<\/span>");
document.write("");
document.write("<span class=\"Googol_Colour_10\">S<\/span>");
document.write("");
document.write("<align=\"center\">");
document.write("");
document.write("<p align=\"center\"><\/p>");
document.write("");
document.write("<span class=\"Googol_Simulator_Font_Colour\">simulator<\/span>");
document.write("");
document.write("<\/div>");
document.write("");
document.write("<p align=\"center\">&nbsp;<\/p>");
document.write("");
document.write("<div class=\"span5\">");
document.write("     ");
document.write("     <div align=\"center\">");
document.write("     ");
document.write("<a href=\"#\" class=\"btn btn-large btn-block\">Default Button<\/a>");
document.write("     ");
document.write("<\/div>");
document.write("");
document.write("");
document.write("<\/div>");
document.write("");

